
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author p_a_u
 */
public class VentanaGrafo extends javax.swing.JFrame {
Grafo grafito = new Grafo();
    String vert="", ari="";
    
    
    /**
     * Creates new form VentanaGrafo
     */
    public VentanaGrafo() {
        this.setLocationRelativeTo(null);
        initComponents();
        lblMensaje.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtOrigen = new javax.swing.JTextField();
        lblVertice = new javax.swing.JLabel();
        lblGrafos = new javax.swing.JLabel();
        btnApply = new javax.swing.JButton();
        lblDest = new javax.swing.JLabel();
        lblVertices = new javax.swing.JLabel();
        lblAristas = new javax.swing.JLabel();
        txtaRista = new javax.swing.JTextField();
        cmbSelecc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtmTriz = new javax.swing.JTextArea();
        cmbVertices = new javax.swing.JComboBox<>();
        lblMensaje = new javax.swing.JLabel();
        cmbDestiny = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        txtOrigen.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtOrigen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOrigenKeyTyped(evt);
            }
        });

        lblVertice.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblVertice.setText("Vertice");

        lblGrafos.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lblGrafos.setText("GRAFOS");

        btnApply.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        lblDest.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblDest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDest.setText("Destino:");

        lblVertices.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblVertices.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVertices.setText("Vertices");

        lblAristas.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblAristas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAristas.setText("Aristas");

        txtaRista.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        cmbSelecc.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cmbSelecc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona:", "Insertar Vertice", "Borrar Vertice", "Insertar Arista", "Borrar Arista", "Matriz Adyacencia", "Lista Adyacencia" }));
        cmbSelecc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSeleccActionPerformed(evt);
            }
        });

        txtmTriz.setColumns(20);
        txtmTriz.setRows(5);
        jScrollPane1.setViewportView(txtmTriz);

        cmbVertices.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        lblMensaje.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje.setText("Para lista de adyacencia ,selecciona en cmbVertices");

        cmbDestiny.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblVertice)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAristas)
                            .addComponent(lblDest, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVertices))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(lblGrafos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtaRista)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                            .addComponent(btnApply, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(cmbVertices, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbDestiny, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbSelecc, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMensaje)))))
                    .addComponent(jScrollPane1))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGrafos)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVertice)
                    .addComponent(btnApply)
                    .addComponent(cmbSelecc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDest)
                    .addComponent(cmbDestiny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVertices)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMensaje)
                        .addComponent(cmbVertices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAristas)
                    .addComponent(txtaRista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSeleccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSeleccActionPerformed
        int opcion = cmbSelecc.getSelectedIndex();
        if(opcion == 1 || opcion == 2){
           
            lblDest.setVisible(true);
            cmbDestiny.setVisible(false);
        }
        if(opcion == 6){
        lblMensaje.setVisible(true);
        }
        else{
            lblMensaje.setVisible(false);
            lblDest.setVisible(true);
            cmbDestiny.setVisible(true);
        }
        
    }//GEN-LAST:event_cmbSeleccActionPerformed

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
         int opcion = cmbSelecc.getSelectedIndex();
         char f=' ', 
         destiny = ' ';
         
        if(opcion<5){
        if(txtOrigen.getText().length()==0){ this.setTitle("¡Ingresa un dato!"); return; }
            f = txtOrigen.getText().toUpperCase().charAt(0);
        }
        if(opcion>2 && opcion<5)  destiny = (char) cmbDestiny.getSelectedItem();
        boolean respuesta;
        
        switch (opcion){
            case 1:
                respuesta = grafito.insertarVertice(f);
                mostrarRespuesta(respuesta); 
                vert+=f+", "; 
                if(respuesta){ cmbVertices.addItem(f);
                cmbDestiny.addItem(f);
                }
            break;
            
            case 2: 
                respuesta = grafito.eliminarVertice(f); 
                mostrarRespuesta(respuesta);  
                if(respuesta) cmbVertices.removeItem(f);
            break;
            
            case 3: 
                respuesta = grafito.insertarArista(f, destiny);  
                mostrarRespuesta(respuesta);
                if(respuesta) ari+=f+","+destiny+" ";
            break;
            
            case 4: 
                respuesta = grafito.eliminarArista(f, destiny);
                mostrarRespuesta(respuesta);
                String aristaEliminada = f+","+destiny; 
                mostrarAristas(respuesta, aristaEliminada);
                
            break;
            
            case 5:
                if(ari.length()==0){ txtmTriz.setText("No tienes aristas para ejecutar Matriz "); return;}
                String help1 = vert.replaceAll(", ", ""); 
                
                
                
                char [] help = help1.toCharArray();
                boolean datos[][] = grafito.matrizAdyacencia();
                String cad = "";
                for (int i = 0; i < help.length; i++) {
                    cad += help[i];
                }

                for (int i = 0; i < help.length; i++) {
                    cad += "\n" + help[i] + " ";
                    for (int j = 0; j < help.length; j++) {
                        if(datos[i][j]){
                            cad+="1 ";
                        }else{
                            cad+="0 ";
                        }
                    }
                }
                txtmTriz.setText(cad);
            break;
            
            case 6: 
                if (cmbVertices.getItemCount() > 0)//Verifica cuanto elementos tiene la lista
                txtmTriz.setText(grafito.listaAdyacencia((char) cmbVertices.getSelectedItem()));
            break;    
        }
        
        if(cmbSelecc.getSelectedIndex()!=4){ 
            txtaRista.setText(ari); 
        }
         
    }//GEN-LAST:event_btnApplyActionPerformed

    private void txtOrigenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOrigenKeyTyped
char validar =evt.getKeyChar();
if(Character.isDigit(validar)){
getToolkit().beep();
evt.consume();
showMessageDialog(rootPane,"Ingresar solo letras");

        }
    }//GEN-LAST:event_txtOrigenKeyTyped

    
    
    
    public void mostrarAristas(boolean respuesta, String aristaEliminada){
        String[] arisTas = ari.split(" ");
            if(respuesta){
                ari ="";
                String cad="";
                for(int i=0; i<arisTas.length; i++){
                    if(arisTas[i].equals(aristaEliminada)){
                        cad+= "";
                        ari += "";
                    }else{
                        cad = cad+arisTas[i]+" ";
                        ari += arisTas[i]+" ";
                        }
                    }
                    txtaRista.setText(cad);
            }
    }
    
    public void mostrarRespuesta(boolean respuesta){
        String mensaje = "Inserción/Eliminación erronea";
        if(respuesta) mensaje = "Operacion Realizada";
        setTitle(mensaje);
        txtOrigen.setText("");
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGrafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGrafo().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JComboBox<Character> cmbDestiny;
    private javax.swing.JComboBox<String> cmbSelecc;
    private javax.swing.JComboBox<Character> cmbVertices;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAristas;
    private javax.swing.JLabel lblDest;
    private javax.swing.JLabel lblGrafos;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblVertice;
    private javax.swing.JLabel lblVertices;
    private javax.swing.JTextField txtOrigen;
    private javax.swing.JTextField txtaRista;
    private javax.swing.JTextArea txtmTriz;
    // End of variables declaration//GEN-END:variables
}
